### ISSUE TITLE
Idea for collaboration

### ISSUE THREAD

**Issue by orschiro** [sidenotes/sidenotes#78]
Dear all, 

What a fantastic product that you had created with sidenotes. Congratulations!

I would like to hear your opinion on working together on a project that I have started under the name [Plain Text Life](https://github.com/orschiro/plain-text-life) because I feel that we share many commonalities. 

I created the [today.txt](https://github.com/orschiro/plain-text-life/blob/master/today.txt) template to help people structure their day meaningfully. 

What I would envision is that people can visit a website, e.g. plainlife.co/io, on which they are directly presented with the latest version of the template. They can edit the template over the entire day and changes are automatically synced to their private Dropbox, giving the text file the current date. 

The technology you created for sidenotes seems to fit this purpose very well. 

Thus my question to you, would you be interested in working together on this idea to help people to go through their day in a more meaningful way?

Thankfully,

Robert

**Comment by stefankp** [comment]
@orschiro you can use this code as a starting point if you are interested, it's open source.

**Comment by orschiro** [comment]
Thank you for your comment @stefankp!

Appreciated, 

~Robert
